import { Link } from 'react-router-dom';
import NetBackground from '../components/NetBackground';

export default function Security() {
  return (
    <>
      <title>Security | Connex Technologies | How We Protect Payment Proof Infrastructure</title>

      <section className="page-hero" aria-labelledby="sec-hero-h">
        <NetBackground />
        <div className="wrap">
          <span className="eyebrow">Security</span>
          <h1 id="sec-hero-h">Built to hold<br />up to scrutiny.</h1>
          <p className="lead">Connex handles proof infrastructure for cross-institutional payment handoffs. The security of that infrastructure is not a feature - it is the product. Here is how we build it.</p>
        </div>
      </section>

      {/* PRINCIPLES */}
      <section className="section" aria-labelledby="sec-principles-h">
        <div className="wrap">
          <div className="sec-head reveal">
            <span className="eyebrow">Security Architecture</span>
            <h2 className="h2 display" id="sec-principles-h">How we protect the proof layer.</h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(min(100%, 340px), 1fr))', gap: 'clamp(14px, 1.4vw, 22px)' }}>
            <div className="sec-card reveal">
              <span className="c-key">Cryptographic Integrity</span>
              <h3>Tamper-Evident Proof Bundles</h3>
              <p>Every proof bundle generated by Connex is cryptographically signed. Any alteration to a proof record after the fact, by any party, including Connex, is mathematically detectable. The signature scheme is based on established, publicly documented cryptographic standards.</p>
            </div>
            <div className="sec-card reveal" data-delay="1">
              <span className="c-key">No Single Point of Control</span>
              <h3>Multi-Node Witness Consensus</h3>
              <p>Proofs are generated through a multi-node witness consensus process. No single node, and not Connex itself, can unilaterally generate, alter, or suppress a proof. The architecture is designed so that control over the record is distributed, not centralised.</p>
            </div>
            <div className="sec-card reveal" data-delay="2">
              <span className="c-key">Data Minimisation</span>
              <h3>Zero Knowledge by Design</h3>
              <p>Connex does not capture, store, or process transaction amounts, account numbers, customer names, or personal financial data. We capture only the structural metadata of the handoff, the minimum information needed to generate a verifiable proof, and nothing more.</p>
            </div>
            <div className="sec-card reveal" data-delay="3">
              <span className="c-key">Non-Invasive Architecture</span>
              <h3>No Payment Path Dependency</h3>
              <p>Connex connects alongside existing payment infrastructure without sitting in the transaction path. A security incident at Connex cannot block, delay, or alter any payment. Our infrastructure cannot become a vector for attacking the payment systems we connect to.</p>
            </div>
            <div className="sec-card reveal">
              <span className="c-key">API Security</span>
              <h3>Authenticated and Encrypted</h3>
              <p>All connections to the Connex API are authenticated using institution-specific credentials and encrypted in transit. API access is scoped to the minimum permissions required for each integration, ensuring no institution can access another institution's proof records.</p>
            </div>
            <div className="sec-card reveal" data-delay="1">
              <span className="c-key">Independent Verifiability</span>
              <h3>Verify Without Trusting Us</h3>
              <p>Every proof bundle can be independently verified by any authorised party using standard cryptographic tools. You do not need to trust Connex's systems or processes to validate a proof. The mathematics provides the assurance, not our word.</p>
            </div>
          </div>
        </div>
      </section>

      {/* WHAT WE DON'T DO */}
      <section className="section section--tight" aria-labelledby="sec-no-h">
        <div className="wrap">
          <div className="sec-head reveal">
            <span className="eyebrow">What We Do Not Do</span>
            <h2 className="h2 display" id="sec-no-h">Limits that are not negotiable.</h2>
          </div>
          <div className="neutral-list">
            <div className="neutral-line reveal"><span className="nl-idx">01</span><span className="nl-text">We do not store customer financial data.</span></div>
            <div className="neutral-line reveal" data-delay="1"><span className="nl-idx">02</span><span className="nl-text">We do not sit in the payment path.</span></div>
            <div className="neutral-line reveal" data-delay="2"><span className="nl-idx">03</span><span className="nl-text">We do not have unilateral control over any proof.</span></div>
            <div className="neutral-line reveal" data-delay="3"><span className="nl-idx">04</span><span className="nl-text">We do not share one institution's data with another.</span></div>
          </div>
        </div>
      </section>

      {/* DISCLOSURE */}
      <section className="section section--tight" aria-labelledby="sec-disclosure-h">
        <div className="wrap two-col">
          <div className="reveal">
            <span className="eyebrow">Responsible Disclosure</span>
            <h2 className="h2 display" id="sec-disclosure-h" style={{ marginTop: 22 }}>Report a vulnerability.</h2>
          </div>
          <div className="reveal" data-delay="1" style={{ alignSelf: 'end' }}>
            <p className="lead">If you discover a security vulnerability in any part of the Connex infrastructure, please report it responsibly to <a href="mailto:security@connextechnologies.org" style={{ color: 'var(--ink)', borderBottom: '1px solid var(--line)' }}>security@connextechnologies.org</a>. We take all reports seriously, will investigate promptly, and will communicate directly with the reporter about findings and any remediation steps.</p>
          </div>
        </div>
      </section>

      <section className="section" aria-labelledby="sec-cta-h">
        <div className="wrap cta-final">
          <span className="eyebrow reveal" style={{ justifyContent: 'center' }}>Questions</span>
          <h2 className="h1 display reveal" id="sec-cta-h" style={{ marginTop: 22 }}>Security questions? Ask us directly.</h2>
          <div className="row reveal" data-delay="1" style={{ justifyContent: 'center', marginTop: 40 }}>
            <Link className="btn" to="/contact">Contact Us <span className="arrow">→</span></Link>
            <Link className="btn btn--ghost" to="/resources/whitepaper">Read the Whitepaper</Link>
          </div>
        </div>
      </section>
    </>
  );
}
