import { useState } from 'react';
import { Link } from 'react-router-dom';
import NetBackground from '../../components/NetBackground';

const FAQS = [
  {
    cat: 'What Connex Does',
    items: [
      {
        q: 'What is Connex Technologies?',
        a: 'Connex Technologies is a neutral payment coordination layer for Kenya and Africa. We sit alongside existing payment systems to do two things: automatically enrich outgoing payment messages so they arrive complete and compliant with ISO 20022 standards, and generate tamper-evident cryptographic proof of every cross-institutional payment handoff. We do not move money, process payments, or touch the payment flow in any way.'
      },
      {
        q: 'What problem does Connex solve?',
        a: 'When money moves between two financial institutions, two things consistently fail. First, critical data fields are lost as payment messages pass through different systems, meaning the receiving institution gets an incomplete picture. Second, there is no neutral record of the handoff. Each institution keeps its own log, and when those logs disagree, there is no independent witness. Disputes can take weeks to resolve. Connex solves both problems with a single coordination layer.'
      },
      {
        q: 'How is Connex different from existing payment infrastructure?',
        a: 'Existing payment infrastructure, including PESALINK, SWIFT, M-Pesa, and the core banking systems that connect to them, moves money between institutions. Connex does not compete with any of these. We are not a payment processor, a switch, or a messaging network. We are the neutral witness that watches the handoffs those systems create, fills the data gaps they produce, and keeps the permanent record they do not.'
      },
      {
        q: 'Does Connex store customer financial data?',
        a: 'No. Connex is built on a zero-knowledge principle. We do not store transaction amounts, account numbers, customer names, or any personal financial data. We capture and preserve only the structural information needed to generate a verifiable proof of the handoff - not the contents of what was transferred.'
      },
    ]
  },
  {
    cat: 'Integration and Technical',
    items: [
      {
        q: 'How does an institution connect to Connex?',
        a: 'Institutions connect via a lightweight REST API. Connection is non-invasive: Connex receives event data about payment handoffs without sitting in the payment path itself. Integration is designed to be completed without changes to the existing core banking system architecture.'
      },
      {
        q: 'What happens if Connex goes offline?',
        a: 'Nothing happens to payments. Connex is explicitly designed with zero coupling: if our system is unavailable for any reason, every payment on every connected institution continues without interruption. We are an observation layer, not a dependency. We never become a single point of failure.'
      },
      {
        q: 'What is ISO 20022 and why does it matter?',
        a: 'ISO 20022 is the global standard for financial messaging, adopted by central banks and major payment networks worldwide. It carries significantly more structured data than older formats like ISO 8583. When institutions operate on older formats, which most Kenyan banks still do, payment messages lose ISO 20022 fields when they cross institutional boundaries. Connex automatically enriches legacy messages to ISO 20022 standards, so compliance data that would otherwise be lost arrives intact.'
      },
      {
        q: 'What is a cryptographic proof bundle?',
        a: 'A proof bundle is a tamper-evident record of a payment handoff. It is generated by independent witness nodes, not by either institution involved in the payment, and cryptographically signed in a way that makes any subsequent alteration detectable. Any authorised party can verify the proof independently using standard cryptographic methods. It records what was sent, what was received, and the precise timing of the handoff, without capturing the financial content of the transaction.'
      },
    ]
  },
  {
    cat: 'Legal and Regulatory',
    items: [
      {
        q: 'Are Connex proof records legally admissible in Kenya?',
        a: 'Connex proof records are designed to satisfy the admissibility requirements of the Kenyan Evidence Act for electronic records. The design process included reference to the Act\'s requirements for authentication, integrity, and reliability of electronic evidence. We strongly recommend that any institution seeking to rely on a Connex proof in legal proceedings obtain independent legal advice regarding admissibility in their specific context.'
      },
      {
        q: 'How does Connex relate to CBK regulations?',
        a: 'Connex is building within the Kenyan regulatory framework. We are not a payment service provider, a bank, or a licensed financial institution: we are a technology infrastructure provider. We have studied the CBK\'s regulatory framework, including the National Payment System Act, and our architecture is designed to be compatible with it. We are also actively engaging with relevant stakeholders as our product develops.'
      },
      {
        q: 'Who controls the proof records?',
        a: 'No single party controls a Connex proof record. Proofs are generated by independent witness nodes through a multi-node consensus process, meaning no single institution, and not Connex itself, can unilaterally alter or invalidate a proof. This is the architectural foundation of our neutrality: we are structurally incapable of taking sides.'
      },
    ]
  },
  {
    cat: 'Partnership and Access',
    items: [
      {
        q: 'How do I become a founding partner?',
        a: 'We are currently establishing a founding cohort of institutions in Kenya. Founding partners receive priority access, direct input into the product roadmap, and preferred partnership terms. To begin the conversation, contact us through the form on our Contact page or email info@connextechnologies.org directly.'
      },
      {
        q: 'Is Connex available outside Kenya?',
        a: 'Connex is currently focused on the Kenyan market. Kenya is where we know the institutions, the regulatory environment, and the specific friction points in the payment system. Our intention is to expand across Africa as the founding cohort is established and the product is validated in the Kenyan market.'
      },
      {
        q: 'Where is Connex Technologies based?',
        a: 'Connex Technologies is based in Kenya. We are founded and built in Kenya, for Kenya.'
      },
    ]
  },
];

function FaqItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="faq-item" onClick={() => setOpen(o => !o)} role="button" aria-expanded={open} tabIndex={0} onKeyDown={e => e.key === 'Enter' && setOpen(o => !o)}>
      <div className="faq-q">
        <h3>{q}</h3>
        <span className={`faq-toggle${open ? ' open' : ''}`} aria-hidden="true">+</span>
      </div>
      <div className="faq-a" style={{ maxHeight: open ? 500 : 0, opacity: open ? 1 : 0, overflow: 'hidden', transition: 'max-height 0.4s ease, opacity 0.4s ease' }}>
        <p>{a}</p>
      </div>
    </div>
  );
}

export default function FAQ() {
  return (
    <>
      <title>FAQ | Connex Technologies | Payment Coordination Questions Answered</title>

      <section className="page-hero" aria-labelledby="faq-hero-h">
        <NetBackground />
        <div className="wrap">
          <span className="eyebrow">Resources / FAQ</span>
          <h1 id="faq-hero-h">Questions,<br />answered plainly.</h1>
          <p className="lead">Everything you need to know about how Connex works, how institutions connect, and what the legal and regulatory framework looks like. If your question is not here, contact us directly.</p>
        </div>
      </section>

      <section className="section" aria-label="Frequently asked questions">
        <div className="wrap">
          {FAQS.map(cat => (
            <div key={cat.cat} style={{ marginBottom: 'clamp(48px,8vh,90px)' }}>
              <p className="faq-cat-label reveal">{cat.cat}</p>
              <div className="reveal">
                {cat.items.map(item => <FaqItem key={item.q} q={item.q} a={item.a} />)}
              </div>
            </div>
          ))}

          <div className="status-banner reveal" style={{ marginTop: 'clamp(48px,8vh,80px)' }}>
            <span className="eyebrow" style={{ justifyContent: 'center' }}>Still have questions?</span>
            <h2 className="h3" style={{ marginTop: 22, fontWeight: 800, textTransform: 'uppercase', letterSpacing: '-0.02em' }}>We answer everything in a direct briefing.</h2>
            <p className="muted" style={{ marginTop: 12, maxWidth: '52ch', margin: '12px auto 0' }}>Book a private briefing and we will walk through the full architecture, your integration scenario, and any questions your technical or executive team has.</p>
            <Link className="btn" to="/contact" style={{ marginTop: 28, display: 'inline-flex' }}>Request a Briefing <span className="arrow">→</span></Link>
          </div>
        </div>
      </section>
    </>
  );
}
