import { Link } from 'react-router-dom';
import NetBackground from '../../components/NetBackground';

export default function Regulators() {
  return (
    <>
      <title>Connex for Regulators | Payment Oversight and Evidence Infrastructure | Connex Technologies</title>

      <section className="page-hero" aria-labelledby="regs-hero-h">
        <NetBackground />
        <div className="wrap">
          <span className="eyebrow">Solutions / Regulators</span>
          <h1 id="regs-hero-h">For financial<br />regulators.</h1>
          <p className="lead">Regulators need visibility into cross-institutional payment flows. Today, that visibility depends on self-reported logs from parties with financial interests in the outcome. Connex provides the neutral ground truth.</p>
        </div>
      </section>

      <section className="section section--tight" aria-labelledby="regs-value-h">
        <div className="wrap">
          <div className="sec-head reveal">
            <span className="eyebrow">What Regulators Get</span>
            <h2 className="h2 display" id="regs-value-h">A neutral witness to every handoff.</h2>
          </div>
          <div className="grid-4 reveal">
            <div className="cell">
              <span className="c-key">Oversight</span>
              <h3>Independent Records</h3>
              <p>Connex proof bundles are generated by independent witness nodes, not by any institution involved in the payment. Regulators access a record that no single party could have altered.</p>
            </div>
            <div className="cell">
              <span className="c-key">Investigation</span>
              <h3>Instant Evidence Retrieval</h3>
              <p>When investigating a disputed payment, authorized regulatory staff retrieve the Connex proof bundle directly. No waiting for institutions to reconstruct logs. No conflicting accounts. The evidence is immutable and immediate.</p>
            </div>
            <div className="cell">
              <span className="c-key">Legal Standing</span>
              <h3>Court-Admissible Proofs</h3>
              <p>Proof records are designed to meet the admissibility requirements of the Kenyan Evidence Act, built from the ground up for use in regulatory proceedings and court processes.</p>
            </div>
            <div className="cell">
              <span className="c-key">Systemic View</span>
              <h3>Cross-Institutional Visibility</h3>
              <p>For the first time, it becomes possible to have a coherent, neutral view of how money moves between institutions, without relying on any institution's self-reporting.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="section" aria-labelledby="regs-cta-h">
        <div className="wrap cta-final">
          <span className="eyebrow reveal" style={{ justifyContent: 'center' }}>For Regulators</span>
          <h2 className="h1 display reveal" id="regs-cta-h" style={{ marginTop: 22 }}>Build the oversight infrastructure Africa needs.</h2>
          <div className="row reveal" data-delay="1" style={{ justifyContent: 'center', marginTop: 40 }}>
            <Link className="btn" to="/contact">Start a Conversation <span className="arrow">→</span></Link>
            <Link className="btn btn--ghost" to="/resources/whitepaper">Read the Whitepaper</Link>
          </div>
        </div>
      </section>
    </>
  );
}
